#!/bin/bash
# 
# This script works to reconcile the classification of white matter (WM) hypointensities
# as cortical gray matter (CGM) or cerebrospinal fluid (CSF) within a subject's 5TT image 
# by replacing the original CGM volume generated by FSL FAST with the cortical ribbon
# generated by Freesurfer. Additionally, this script (i) adds the amygdala and hippocampus 
# segmented by freesurfer (rather than those sgmented by FSL FIRST, for superior contiguity
# with the cortical ribbon) to the subcortical gray matter (SGM) volume and (ii) reclassifies 
# any voxels as 100% WM if they meet each of the following criteria:
#
#   1. Voxel is <100% CGM (note that this is not 50% since the cortical ribbon is
#      a binary volume)
#   2. Voxel is <50% subcortical gray matter (SGM)
#   3. Voxel is <100% CSF
#   4. Voxel is not outside the freesurfer aparc mask
#
# The principal benefit of this is to minimize lesion-induced streamline termination:
# since anatomically-constrained tractography will normally terminate streamlines upon
# contacting voxels which are >50% CSF, CGM, or SGM, the common classification of WM 
# lesions as CGM or CSF by FSL FAST risks neglecting the anatomical ground truth that
# axons are capable of traversing through lesions.
# 
# Note that this script requires post-structural to have already been run, in order for
# transformation files beetween freeusrfer space and native space to be callable.
#
# Authored by Daniel O'Sullivan (2024)
#----------------------------------------------------------------------------------#
source '/data_/tardiflab/mwc/mwcpipe/tardiflab/scripts/01_processing/init.sh'

# Define subject-specific variables in micapipe format
id=$1
SES=$2
BIDS=$3
out=$4
modify=$5 # Use this argument to regenerate 5TT in native space and in DWI space (e.g. if you want to modify these images after having already generated them)
nocleanup=$6

ses="_${SES}"
subject=sub-${id}
idBIDS="${subject}${ses}"

if [ -z $1 ]; then
    echo "Subject ID not specified! Exiting."
    exit
elif [ ! -d $BIDS/$subject ]; then
    echo "Subject ID not in ${BIDS}! Exiting."
    exit
fi

if [ -z $2 ]; then
    echo "Subject session not specified! Exiting."
    exit
elif [ ! -d $BIDS/$subject/$SES ]; then
    echo "Subject session '$2' not in ${BIDS}/${subject}! Exiting."
    exit
fi

# Define paths to subject's structural directory and derivatives in micapipe format 
subject_dir=$out/${subject}/${SES}
proc_struct=$subject_dir/anat
orig_CGM=$proc_struct/${idBIDS}_space-nativepro_t1w_brain_pve_1.nii.gz
T1nativepro_brain=${proc_struct}/${idBIDS}_space-nativepro_t1w_brain.nii.gz

dir_warp=$subject_dir/xfm

proc_dwi=$subject_dir/dwi

bids_derivs="${BIDS}/derivatives"
dir_surf=${bids_derivs}/freesurfer
dir_freesurfer=${dir_surf}/${idBIDS}
T1freesurfr=${dir_freesurfer}/mri/T1.mgz
T1freesurfr_brain=${dir_freesurfer}/mri/brainmask.mgz
aseg_auto_in_fs=${dir_freesurfer}/mri/aseg.auto.mgz
if [[ -d ${dir_freesurfer}/mri/OLD_RIBBON ]]; then # Made this directory to store unedited ribbon.mgz for subjects whose ribbon was manually edited
    cerebrum_in_fs=${dir_freesurfer}/mri/OLD_RIBBON/ribbon.mgz
    echo "$subject $SES has an old ribbon folder. Using this file for cerebrum."
else
    cerebrum_in_fs=${dir_freesurfer}/mri/ribbon.mgz
fi

# Create a temporary directory for subsequent processing if it does not yet exist
tmpDir=${out}/tmp_micapipe
tmp=${tmpDir}/new_5tt/${subject}/${SES}
if [[ ! -d $tmp ]]; then
    mkdir -p "$tmp"
fi

# Define path to original 5TT and left/right cortical ribbons
T15ttgen=${proc_struct}/${idBIDS}_space-nativepro_t1w_5TT.nii.gz
lh_ribbon=$dir_freesurfer/mri/lh.ribbon.mgz
rh_ribbon=$dir_freesurfer/mri/rh.ribbon.mgz

#----------------------------------------------------------------------------------#
# Copy original 5TT into separate subdirectory
old_5tt=$proc_struct/old_5tt/${idBIDS}_space-nativepro_t1w_5TT.nii.gz
if [[ ! -f $old_5tt ]]; then
    mkdir -p $proc_struct/old_5tt
    cp $T15ttgen $proc_struct/old_5tt/
fi

#----------------------------------------------------------------------------------#
new_5TT=$tmp/${idBIDS}_space-nativepro_t1w_new5TT.nii.gz
if [[ ! -f $new_5TT || $modify == 'modify' ]]; then
    # Construct subject's whole cortical ribbon from left/right cortical ribbon files
    ribbon_in_fs=$tmp/${idBIDS}_ribbon_in_fs.nii.gz
    if [[ ! -f $ribbon_in_fs ]]; then
        mrconvert -force $lh_ribbon $tmp/lh.ribbon.nii.gz
        mrconvert -force $rh_ribbon $tmp/rh.ribbon.nii.gz
        fslmaths $tmp/lh.ribbon.nii.gz -add $tmp/rh.ribbon.nii.gz $ribbon_in_fs
    fi

    # Transform cortical ribbon, hippocampus/amygdala, and aparc mask from freesurfer space to native space
    ribbon_native=${tmp}/${idBIDS}_ribbon_native.nii.gz # Cortical ribbon

    aseg_auto_fsdims=${tmp}/${idBIDS}_fsdims_aseg.auto.nii.gz # Freesurfer aparc
    aseg_auto_nativedims=${tmp}/${idBIDS}_nativedims_aseg.auto.nii.gz
    aseg_auto_native=${tmp}/${idBIDS}_aseg.auto.nii.gz

    cerebrum_fsdims=${tmp}/${idBIDS}_fsdims_cerebrum.nii.gz # Freesurfer aparc
    cerebrum_nativedims=${tmp}/${idBIDS}_nativedims_cerebrum.nii.gz
    cerebrum_native=${tmp}/${idBIDS}_cerebrum.nii.gz

    mat_fsnative_affine=${dir_warp}/${idBIDS}_from-fsnative_to_nativepro_t1w_ # Pre-existing transformation matrices
    T1_fsnative_affine=${mat_fsnative_affine}0GenericAffine.mat

    if [[ ! -f "$ribbon_native" || ! -f $aseg_auto_native || $cerebrum_native ]]; then
        mrconvert -force $aseg_auto_in_fs $aseg_auto_fsdims
        mrconvert -force $cerebrum_in_fs $cerebrum_nativedims
        antsApplyTransforms -d 3 -i "$ribbon_in_fs" -r "$orig_CGM" -t ["${T1_fsnative_affine}"] -o "$ribbon_native" -v -u int -n NearestNeighbor
        antsApplyTransforms -d 3 -i "$aseg_auto_fsdims" -r "$T1nativepro_brain" -t ["${T1_fsnative_affine}"] -o "$aseg_auto_native" -v -u int -n NearestNeighbor
        antsApplyTransforms -d 3 -i "$cerebrum_nativedims" -r "$T1nativepro_brain" -t ["${T1_fsnative_affine}"] -o "$cerebrum_native" -v -u int -n NearestNeighbor
    fi

    # Replace CGM in 5TT with cortical ribbon
    echo "Replacing CGM volume in original 5TT in with cortical ribbon..."

    str_5tt=$(basename $T15ttgen)
    T15ttgen_mif=$tmp/${str_5tt/.nii.gz/.mif}
    T15ttgen_noCGM=${T15ttgen_mif/.mif/_noCGM.mif}
    T15ttgen_newCGM=${T15ttgen_mif/.mif/_newCGM.mif}
    T15ttgen_newCGM_nii=${T15ttgen_newCGM/.mif/.nii.gz}

    if [[ ! -f $T15ttgen_newCGM_nii ]]; then
        # Convert 5TT to .mif format
        mrconvert $T15ttgen $T15ttgen_mif

        # Generate new 5TT without first volume (CGM)
        mrconvert $T15ttgen_mif -coord 3 1:1:4 $T15ttgen_noCGM

        # Add cortical ribbon as new CGM
        mrcat $ribbon_native $T15ttgen_noCGM $T15ttgen_newCGM

        # Convert 5TT with new CGM back to .nii.gz format
        mrconvert $T15ttgen_newCGM $T15ttgen_newCGM_nii
    fi

    # If a voxel is <100% CGM, <50% SGM, and <100% CSF, it will be redefined as 100% WM
    # NOTE: Discrepancy between CGM and SGM thresholds is due to the binary nature of new CGM
    echo "Redefining any voxels that are <50% CGM, <50% SGM, and <100% CSF as WM..."

    if [[ ! -f $tmp/WM_mask.nii.gz ]]; then
        # Split 5TT into its constituent volumes an binarize them according to thresholds
        fslsplit $T15ttgen_newCGM_nii $tmp/"vol_" -t
        fslmaths $tmp/vol_0000.nii.gz -thr 1.0 -bin $tmp/CGM_mask.nii.gz
        fslmaths $tmp/vol_0001.nii.gz -thr 0.5 -bin $tmp/SGM_mask.nii.gz
        fslmaths $tmp/vol_0003.nii.gz -thr 1.0 -bin $tmp/CSF_mask.nii.gz
        pathological_vol=$tmp/vol_0004.nii.gz

        # Add amygdala and hippocampus to SGM_mask (use Freesurfer segmentations for contiguity with cortical ribbon)
        fslmaths $aseg_auto_native -thr 17 -uthr 17 -bin $tmp/l_hipp.nii.gz
        fslmaths $aseg_auto_native -thr 18 -uthr 18 -bin $tmp/l_amy.nii.gz
        fslmaths $aseg_auto_native -thr 53 -uthr 53 -bin $tmp/r_hipp.nii.gz
        fslmaths $aseg_auto_native -thr 54 -uthr 54 -bin $tmp/r_amy.nii.gz
        fslmaths $tmp/SGM_mask.nii.gz -add $tmp/l_hipp.nii.gz -add $tmp/l_amy.nii.gz -add $tmp/r_hipp.nii.gz -add $tmp/r_amy.nii.gz $tmp/SGM_mask.nii.gz

        # Combine non-WM tissue types
        fslmaths $tmp/CGM_mask.nii.gz -add $tmp/SGM_mask.nii.gz -add $tmp/CSF_mask.nii.gz $tmp/sum_of_CGM-SGM-CSF_masks.nii.gz

        # Apply freesurfer brain mask to WM mask so that non-brain regions are not declared WM
        # Extract brainstem, cerebellar WM, cerebral WM, and WMHs for WM mask
        fslmaths $aseg_auto_native -thr 16 -uthr 16 -bin $tmp/brainstem.nii.gz
        fslmaths $aseg_auto_native -thr 7 -uthr 7 -bin $tmp/l_cblm_wm.nii.gz
        fslmaths $aseg_auto_native -thr 46 -uthr 46 -bin $tmp/r_cblm_wm.nii.gz
        fslmaths $aseg_auto_native -thr 2 -uthr 2 -bin $tmp/l_cbm_wm.nii.gz # Add because ribbon.mgz can miss a few voxels bordering hippocampus/amygdala
        fslmaths $aseg_auto_native -thr 41 -uthr 41 -bin $tmp/r_cbm_wm.nii.gz # Add because ribbon.mgz can miss a few voxels bordering hippocampus/amygdala
        fslmaths $aseg_auto_native -thr 77 -uthr 77 -bin $tmp/WMH.nii.gz

        # Extract voxels with >50% WM from original FSL FAST WM volume to ensure corpus callosum is included (manual extraction from aseg.auto.mgz ran into errors)
        fslsplit $old_5tt $tmp/"old_vol_" -t
        fslmaths $tmp/old_vol_0002.nii.gz -thr 0.5 $tmp/FSL_FAST_WM.nii.gz

        fslmaths $tmp/brainstem.nii.gz -add $tmp/r_cblm_wm.nii.gz -add $tmp/l_cblm_wm.nii.gz -add $tmp/r_cbm_wm.nii.gz -add $tmp/l_cbm_wm.nii.gz -add $tmp/WMH.nii.gz -add $tmp/FSL_FAST_WM.nii.gz $tmp/WM_mask.nii.gz

        # Add binarization of ribbon.mgz rather binarization of aseg since CGM volume is thinner in ribbon.mgz than in aseg (thus, using aseg would cause extracortical WM)
        fslmaths $cerebrum_native -bin $tmp/cerebrum_mask.nii.gz
        fslmaths $tmp/WM_mask.nii.gz -add $tmp/cerebrum_mask.nii.gz $tmp/WM_mask.nii.gz
        fslmaths $tmp/WM_mask.nii.gz -bin $tmp/WM_mask.nii.gz
        
        # Exclude CGM, SGM, and CSF from WM mask
        fslmaths $tmp/WM_mask.nii.gz -sub $tmp/sum_of_CGM-SGM-CSF_masks.nii.gz $tmp/WM_mask.nii.gz
        fslmaths $tmp/WM_mask.nii.gz -bin $tmp/WM_mask.nii.gz

        # Print message if any voxels meet search criteria
        nonzero_voxels=$(fslstats $tmp/WM_mask.nii.gz -V | awk '{print $1}')
        WM_volume=$(( $nonzero_voxels/1000 ))
        echo "A total of $nonzero_voxels voxels ($WM_volume cm^3) will be declared WM."
    fi

    # Create final new 5TT by concatenating new tissue masks
    mrcat -force $tmp/CGM_mask.nii.gz $tmp/SGM_mask.nii.gz $tmp/WM_mask.nii.gz $tmp/CSF_mask.nii.gz $pathological_vol $new_5TT

fi


# Replace old 5TT with new 5TT, if it has been succesfully generated
if [[ -f $new_5TT ]]; then
    rm $T15ttgen
    cp $new_5TT $T15ttgen
fi

# Remove any existing copy of the 5TT in DWI space. After this, re-run proc-dwi to regenerate it with the new and improved 5TT.
dwi_5tt="${proc_dwi}/${idBIDS}_space-dwi_desc-5tt.nii.gz"
if [[ -f $dwi_5tt ]]; then
    rm $dwi_5tt
    #'/data_/tardiflab/mwc/mwcpipe/micapipe' -sub $id -bids /data_/tardiflab2/danielos/PAD_input -out '/data_/tardiflab2/danielos/output_micapipe' -ses $SES -proc_dwi -dwi_main /data_/tardiflab2/danielos/PAD_input/"sub-$id"/$SES/dwi/*.nii.gz -dwi_rpe /data_/tardiflab2/danielos/PAD_input/"sub-$id"/$SES/fmap/*.nii.gz -dwi_upscale
fi

# Clean up temporary directory
if [[ $nocleanup != "nocleanup" ]]; then
    for i in $tmp/*; do
        rm $i
    done
fi

